[package]
name = "whecko"
version = "0.1.0"
authors = ["Simon Bergstr√∂m <simon@menuan.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = '1.0'
log = '0.4.8'
env_logger = '0.6.2'